"""Adding books.

Revision ID: 2456eda02339
Revises: e43756e3f269
Create Date: 2025-11-17 18:27:13.666552

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2456eda02339"
down_revision = "e43756e3f269"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("authors", sa.String(length=1024), nullable=False),
        sa.Column("language", sa.CHAR(length=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isbn", sa.CHAR(length=13), nullable=False),
        sa.Column("genre", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("isbn"),
    )
    op.create_table(
        "user_books",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "book_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_books")
    op.drop_table("book")
    # ### end Alembic commands ###
