"""Adding invite codes.

Revision ID: 26e5d53b798c
Revises: 2456eda02339
Create Date: 2025-11-17 18:57:00.514780

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "26e5d53b798c"
down_revision = "2456eda02339"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.alter_column(
            "authors",
            existing_type=postgresql.ARRAY(sa.VARCHAR(length=128)),
            type_=sa.String(length=1024),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.alter_column(
            "authors",
            existing_type=sa.String(length=1024),
            type_=postgresql.ARRAY(sa.VARCHAR(length=128)),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
