"""Adding invite codes.

Revision ID: bc3f644b5d8e
Revises:
Create Date: 2025-11-06 09:13:03.011299

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc3f644b5d8e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_code",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.CHAR(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invite_code")
    # ### end Alembic commands ###
