"""Adding users.

Revision ID: e43756e3f269
Revises: bc3f644b5d8e
Create Date: 2025-11-17 10:49:57.964703

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e43756e3f269"
down_revision = "bc3f644b5d8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("invite_code_id", sa.Integer(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invite_code_id"],
            ["invite_code.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("invite_code_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
